"""add access level to directories

Revision ID: d1c7e9d37f73
Revises: d2e8c58272a2
Create Date: 2026-04-27 12:10:04.672806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c7e9d37f73'
down_revision: Union[str, Sequence[str], None] = 'd2e8c58272a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('public_link', sa.UUID(), nullable=False))
    op.add_column('directories', sa.Column('access_level', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('files_parent_uid_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'directories', ['parent_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_parent_uid_fkey'), 'files', 'directories', ['parent_uid'], ['uid'])
    op.drop_column('directories', 'access_level')
    op.drop_column('directories', 'public_link')
    # ### end Alembic commands ###
